name = "TenSynth"
uuid = "b5240124-5457-4b0f-b35a-ccf65f7f62fa"
version = "0.1.0"
authors = ["Joe"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[weakdeps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extensions]
TenSynthPyCallExt = "PyCall"

[compat]
Arpack = "0.5"
ITensorMPS = "0.1, 0.2, 0.3"
ITensors = "0.3, 0.6, 0.7, 0.8"
JLD2 = "0.5, 0.6"
JSON = "0.21"
LineSearches = "7"
LinearMaps = "3"
Optim = "1"
TensorOperations = "4, 5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[targets]
test = ["Test"]
